// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL plugin from the GraphQL queries it found.
// It should not be modified by hand.
//
package /Users/kostya/Documents/workProject/Kcell/core/com.alabs/src/main/graphql;

import com.apollographql.apollo.api.Operation;
import com.apollographql.apollo.api.OperationName;
import com.apollographql.apollo.api.Query;
import com.apollographql.apollo.api.Response;
import com.apollographql.apollo.api.ResponseField;
import com.apollographql.apollo.api.ScalarTypeAdapters;
import com.apollographql.apollo.api.internal.OperationRequestBodyComposer;
import com.apollographql.apollo.api.internal.QueryDocumentMinifier;
import com.apollographql.apollo.api.internal.ResponseFieldMapper;
import com.apollographql.apollo.api.internal.ResponseFieldMarshaller;
import com.apollographql.apollo.api.internal.ResponseReader;
import com.apollographql.apollo.api.internal.ResponseWriter;
import com.apollographql.apollo.api.internal.SimpleOperationResponseParser;
import com.apollographql.apollo.api.internal.UnmodifiableMapBuilder;
import com.apollographql.apollo.api.internal.Utils;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Collections;
import java.util.List;
import okio.Buffer;
import okio.BufferedSource;
import okio.ByteString;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

public final class HomeModuleQuery implements Query<HomeModuleQuery.Data, HomeModuleQuery.Data, Operation.Variables> {
  public static final String OPERATION_ID = "12e4006dc9e74c1822a0479e689043c2a422f89006b7f506be2c836c0dafd137";

  public static final String QUERY_DOCUMENT = QueryDocumentMinifier.minify(
    "query HomeModule {\n"
        + "  seo_data(projects: \"eq:edu\") {\n"
        + "    __typename\n"
        + "    title\n"
        + "    description\n"
        + "    keywords {\n"
        + "      __typename\n"
        + "      tag\n"
        + "    }\n"
        + "    meta_tags {\n"
        + "      __typename\n"
        + "      key\n"
        + "      value\n"
        + "    }\n"
        + "  }\n"
        + "}"
  );

  public static final OperationName OPERATION_NAME = new OperationName() {
    @Override
    public String name() {
      return "HomeModule";
    }
  };

  private final Operation.Variables variables;

  public HomeModuleQuery() {
    this.variables = Operation.EMPTY_VARIABLES;
  }

  @Override
  public String operationId() {
    return OPERATION_ID;
  }

  @Override
  public String queryDocument() {
    return QUERY_DOCUMENT;
  }

  @Override
  public HomeModuleQuery.Data wrapData(HomeModuleQuery.Data data) {
    return data;
  }

  @Override
  public Operation.Variables variables() {
    return variables;
  }

  @Override
  public ResponseFieldMapper<HomeModuleQuery.Data> responseFieldMapper() {
    return new Data.Mapper();
  }

  public static Builder builder() {
    return new Builder();
  }

  @Override
  public OperationName name() {
    return OPERATION_NAME;
  }

  @Override
  @NotNull
  public Response<HomeModuleQuery.Data> parse(@NotNull final BufferedSource source,
      @NotNull final ScalarTypeAdapters scalarTypeAdapters) throws IOException {
    return SimpleOperationResponseParser.parse(source, this, scalarTypeAdapters);
  }

  @Override
  @NotNull
  public Response<HomeModuleQuery.Data> parse(@NotNull final ByteString byteString,
      @NotNull final ScalarTypeAdapters scalarTypeAdapters) throws IOException {
    return parse(new Buffer().write(byteString), scalarTypeAdapters);
  }

  @Override
  @NotNull
  public Response<HomeModuleQuery.Data> parse(@NotNull final BufferedSource source) throws
      IOException {
    return parse(source, ScalarTypeAdapters.DEFAULT);
  }

  @Override
  @NotNull
  public Response<HomeModuleQuery.Data> parse(@NotNull final ByteString byteString) throws
      IOException {
    return parse(byteString, ScalarTypeAdapters.DEFAULT);
  }

  @Override
  @NotNull
  public ByteString composeRequestBody(@NotNull final ScalarTypeAdapters scalarTypeAdapters) {
    return OperationRequestBodyComposer.compose(this, false, true, scalarTypeAdapters);
  }

  @NotNull
  @Override
  public ByteString composeRequestBody() {
    return OperationRequestBodyComposer.compose(this, false, true, ScalarTypeAdapters.DEFAULT);
  }

  @Override
  @NotNull
  public ByteString composeRequestBody(final boolean autoPersistQueries,
      final boolean withQueryDocument, @NotNull final ScalarTypeAdapters scalarTypeAdapters) {
    return OperationRequestBodyComposer.compose(this, autoPersistQueries, withQueryDocument, scalarTypeAdapters);
  }

  public static final class Builder {
    Builder() {
    }

    public HomeModuleQuery build() {
      return new HomeModuleQuery();
    }
  }

  /**
   * Data from the response after executing this GraphQL operation
   */
  public static class Data implements Operation.Data {
    static final ResponseField[] $responseFields = {
      ResponseField.forList("seo_data", "seo_data", new UnmodifiableMapBuilder<String, Object>(1)
      .put("projects", "eq:edu")
      .build(), true, Collections.<ResponseField.Condition>emptyList())
    };

    final @Nullable List<Seo_datum> seo_data;

    private transient volatile String $toString;

    private transient volatile int $hashCode;

    private transient volatile boolean $hashCodeMemoized;

    public Data(@Nullable List<Seo_datum> seo_data) {
      this.seo_data = seo_data;
    }

    /**
     * SEO данные для разделов
     */
    public @Nullable List<Seo_datum> seo_data() {
      return this.seo_data;
    }

    @SuppressWarnings({"rawtypes", "unchecked"})
    public ResponseFieldMarshaller marshaller() {
      return new ResponseFieldMarshaller() {
        @Override
        public void marshal(ResponseWriter writer) {
          writer.writeList($responseFields[0], seo_data, new ResponseWriter.ListWriter() {
            @Override
            public void write(List items, ResponseWriter.ListItemWriter listItemWriter) {
              for (Object item : items) {
                listItemWriter.writeObject(((Seo_datum) item).marshaller());
              }
            }
          });
        }
      };
    }

    @Override
    public String toString() {
      if ($toString == null) {
        $toString = "Data{"
          + "seo_data=" + seo_data
          + "}";
      }
      return $toString;
    }

    @Override
    public boolean equals(Object o) {
      if (o == this) {
        return true;
      }
      if (o instanceof Data) {
        Data that = (Data) o;
        return ((this.seo_data == null) ? (that.seo_data == null) : this.seo_data.equals(that.seo_data));
      }
      return false;
    }

    @Override
    public int hashCode() {
      if (!$hashCodeMemoized) {
        int h = 1;
        h *= 1000003;
        h ^= (seo_data == null) ? 0 : seo_data.hashCode();
        $hashCode = h;
        $hashCodeMemoized = true;
      }
      return $hashCode;
    }

    public static final class Mapper implements ResponseFieldMapper<Data> {
      final Seo_datum.Mapper seo_datumFieldMapper = new Seo_datum.Mapper();

      @Override
      public Data map(ResponseReader reader) {
        final List<Seo_datum> seo_data = reader.readList($responseFields[0], new ResponseReader.ListReader<Seo_datum>() {
          @Override
          public Seo_datum read(ResponseReader.ListItemReader listItemReader) {
            return listItemReader.readObject(new ResponseReader.ObjectReader<Seo_datum>() {
              @Override
              public Seo_datum read(ResponseReader reader) {
                return seo_datumFieldMapper.map(reader);
              }
            });
          }
        });
        return new Data(seo_data);
      }
    }
  }

  /**
   * SEO данные для разделов
   */
  public static class Seo_datum {
    static final ResponseField[] $responseFields = {
      ResponseField.forString("__typename", "__typename", null, false, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forString("title", "title", null, true, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forString("description", "description", null, true, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forList("keywords", "keywords", null, true, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forList("meta_tags", "meta_tags", null, true, Collections.<ResponseField.Condition>emptyList())
    };

    final @NotNull String __typename;

    final @Nullable String title;

    final @Nullable String description;

    final @Nullable List<Keyword> keywords;

    final @Nullable List<Meta_tag> meta_tags;

    private transient volatile String $toString;

    private transient volatile int $hashCode;

    private transient volatile boolean $hashCodeMemoized;

    public Seo_datum(@NotNull String __typename, @Nullable String title,
        @Nullable String description, @Nullable List<Keyword> keywords,
        @Nullable List<Meta_tag> meta_tags) {
      this.__typename = Utils.checkNotNull(__typename, "__typename == null");
      this.title = title;
      this.description = description;
      this.keywords = keywords;
      this.meta_tags = meta_tags;
    }

    public @NotNull String __typename() {
      return this.__typename;
    }

    public @Nullable String title() {
      return this.title;
    }

    public @Nullable String description() {
      return this.description;
    }

    public @Nullable List<Keyword> keywords() {
      return this.keywords;
    }

    public @Nullable List<Meta_tag> meta_tags() {
      return this.meta_tags;
    }

    @SuppressWarnings({"rawtypes", "unchecked"})
    public ResponseFieldMarshaller marshaller() {
      return new ResponseFieldMarshaller() {
        @Override
        public void marshal(ResponseWriter writer) {
          writer.writeString($responseFields[0], __typename);
          writer.writeString($responseFields[1], title);
          writer.writeString($responseFields[2], description);
          writer.writeList($responseFields[3], keywords, new ResponseWriter.ListWriter() {
            @Override
            public void write(List items, ResponseWriter.ListItemWriter listItemWriter) {
              for (Object item : items) {
                listItemWriter.writeObject(((Keyword) item).marshaller());
              }
            }
          });
          writer.writeList($responseFields[4], meta_tags, new ResponseWriter.ListWriter() {
            @Override
            public void write(List items, ResponseWriter.ListItemWriter listItemWriter) {
              for (Object item : items) {
                listItemWriter.writeObject(((Meta_tag) item).marshaller());
              }
            }
          });
        }
      };
    }

    @Override
    public String toString() {
      if ($toString == null) {
        $toString = "Seo_datum{"
          + "__typename=" + __typename + ", "
          + "title=" + title + ", "
          + "description=" + description + ", "
          + "keywords=" + keywords + ", "
          + "meta_tags=" + meta_tags
          + "}";
      }
      return $toString;
    }

    @Override
    public boolean equals(Object o) {
      if (o == this) {
        return true;
      }
      if (o instanceof Seo_datum) {
        Seo_datum that = (Seo_datum) o;
        return this.__typename.equals(that.__typename)
         && ((this.title == null) ? (that.title == null) : this.title.equals(that.title))
         && ((this.description == null) ? (that.description == null) : this.description.equals(that.description))
         && ((this.keywords == null) ? (that.keywords == null) : this.keywords.equals(that.keywords))
         && ((this.meta_tags == null) ? (that.meta_tags == null) : this.meta_tags.equals(that.meta_tags));
      }
      return false;
    }

    @Override
    public int hashCode() {
      if (!$hashCodeMemoized) {
        int h = 1;
        h *= 1000003;
        h ^= __typename.hashCode();
        h *= 1000003;
        h ^= (title == null) ? 0 : title.hashCode();
        h *= 1000003;
        h ^= (description == null) ? 0 : description.hashCode();
        h *= 1000003;
        h ^= (keywords == null) ? 0 : keywords.hashCode();
        h *= 1000003;
        h ^= (meta_tags == null) ? 0 : meta_tags.hashCode();
        $hashCode = h;
        $hashCodeMemoized = true;
      }
      return $hashCode;
    }

    public static final class Mapper implements ResponseFieldMapper<Seo_datum> {
      final Keyword.Mapper keywordFieldMapper = new Keyword.Mapper();

      final Meta_tag.Mapper meta_tagFieldMapper = new Meta_tag.Mapper();

      @Override
      public Seo_datum map(ResponseReader reader) {
        final String __typename = reader.readString($responseFields[0]);
        final String title = reader.readString($responseFields[1]);
        final String description = reader.readString($responseFields[2]);
        final List<Keyword> keywords = reader.readList($responseFields[3], new ResponseReader.ListReader<Keyword>() {
          @Override
          public Keyword read(ResponseReader.ListItemReader listItemReader) {
            return listItemReader.readObject(new ResponseReader.ObjectReader<Keyword>() {
              @Override
              public Keyword read(ResponseReader reader) {
                return keywordFieldMapper.map(reader);
              }
            });
          }
        });
        final List<Meta_tag> meta_tags = reader.readList($responseFields[4], new ResponseReader.ListReader<Meta_tag>() {
          @Override
          public Meta_tag read(ResponseReader.ListItemReader listItemReader) {
            return listItemReader.readObject(new ResponseReader.ObjectReader<Meta_tag>() {
              @Override
              public Meta_tag read(ResponseReader reader) {
                return meta_tagFieldMapper.map(reader);
              }
            });
          }
        });
        return new Seo_datum(__typename, title, description, keywords, meta_tags);
      }
    }
  }

  /**
   * Теги
   */
  public static class Keyword {
    static final ResponseField[] $responseFields = {
      ResponseField.forString("__typename", "__typename", null, false, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forString("tag", "tag", null, true, Collections.<ResponseField.Condition>emptyList())
    };

    final @NotNull String __typename;

    final @Nullable String tag;

    private transient volatile String $toString;

    private transient volatile int $hashCode;

    private transient volatile boolean $hashCodeMemoized;

    public Keyword(@NotNull String __typename, @Nullable String tag) {
      this.__typename = Utils.checkNotNull(__typename, "__typename == null");
      this.tag = tag;
    }

    public @NotNull String __typename() {
      return this.__typename;
    }

    public @Nullable String tag() {
      return this.tag;
    }

    @SuppressWarnings({"rawtypes", "unchecked"})
    public ResponseFieldMarshaller marshaller() {
      return new ResponseFieldMarshaller() {
        @Override
        public void marshal(ResponseWriter writer) {
          writer.writeString($responseFields[0], __typename);
          writer.writeString($responseFields[1], tag);
        }
      };
    }

    @Override
    public String toString() {
      if ($toString == null) {
        $toString = "Keyword{"
          + "__typename=" + __typename + ", "
          + "tag=" + tag
          + "}";
      }
      return $toString;
    }

    @Override
    public boolean equals(Object o) {
      if (o == this) {
        return true;
      }
      if (o instanceof Keyword) {
        Keyword that = (Keyword) o;
        return this.__typename.equals(that.__typename)
         && ((this.tag == null) ? (that.tag == null) : this.tag.equals(that.tag));
      }
      return false;
    }

    @Override
    public int hashCode() {
      if (!$hashCodeMemoized) {
        int h = 1;
        h *= 1000003;
        h ^= __typename.hashCode();
        h *= 1000003;
        h ^= (tag == null) ? 0 : tag.hashCode();
        $hashCode = h;
        $hashCodeMemoized = true;
      }
      return $hashCode;
    }

    public static final class Mapper implements ResponseFieldMapper<Keyword> {
      @Override
      public Keyword map(ResponseReader reader) {
        final String __typename = reader.readString($responseFields[0]);
        final String tag = reader.readString($responseFields[1]);
        return new Keyword(__typename, tag);
      }
    }
  }

  /**
   * MapEntry
   */
  public static class Meta_tag {
    static final ResponseField[] $responseFields = {
      ResponseField.forString("__typename", "__typename", null, false, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forString("key", "key", null, true, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forString("value", "value", null, true, Collections.<ResponseField.Condition>emptyList())
    };

    final @NotNull String __typename;

    final @Nullable String key;

    final @Nullable String value;

    private transient volatile String $toString;

    private transient volatile int $hashCode;

    private transient volatile boolean $hashCodeMemoized;

    public Meta_tag(@NotNull String __typename, @Nullable String key, @Nullable String value) {
      this.__typename = Utils.checkNotNull(__typename, "__typename == null");
      this.key = key;
      this.value = value;
    }

    public @NotNull String __typename() {
      return this.__typename;
    }

    public @Nullable String key() {
      return this.key;
    }

    public @Nullable String value() {
      return this.value;
    }

    @SuppressWarnings({"rawtypes", "unchecked"})
    public ResponseFieldMarshaller marshaller() {
      return new ResponseFieldMarshaller() {
        @Override
        public void marshal(ResponseWriter writer) {
          writer.writeString($responseFields[0], __typename);
          writer.writeString($responseFields[1], key);
          writer.writeString($responseFields[2], value);
        }
      };
    }

    @Override
    public String toString() {
      if ($toString == null) {
        $toString = "Meta_tag{"
          + "__typename=" + __typename + ", "
          + "key=" + key + ", "
          + "value=" + value
          + "}";
      }
      return $toString;
    }

    @Override
    public boolean equals(Object o) {
      if (o == this) {
        return true;
      }
      if (o instanceof Meta_tag) {
        Meta_tag that = (Meta_tag) o;
        return this.__typename.equals(that.__typename)
         && ((this.key == null) ? (that.key == null) : this.key.equals(that.key))
         && ((this.value == null) ? (that.value == null) : this.value.equals(that.value));
      }
      return false;
    }

    @Override
    public int hashCode() {
      if (!$hashCodeMemoized) {
        int h = 1;
        h *= 1000003;
        h ^= __typename.hashCode();
        h *= 1000003;
        h ^= (key == null) ? 0 : key.hashCode();
        h *= 1000003;
        h ^= (value == null) ? 0 : value.hashCode();
        $hashCode = h;
        $hashCodeMemoized = true;
      }
      return $hashCode;
    }

    public static final class Mapper implements ResponseFieldMapper<Meta_tag> {
      @Override
      public Meta_tag map(ResponseReader reader) {
        final String __typename = reader.readString($responseFields[0]);
        final String key = reader.readString($responseFields[1]);
        final String value = reader.readString($responseFields[2]);
        return new Meta_tag(__typename, key, value);
      }
    }
  }
}
